### PR TITLE
Feat py3k

### PR DESCRIPTION
**Pull request by larroy**
Ported to py3

### CODE REVIEW

**Comment by superbobry** [comment]
Thank you for contributing. Can you please change your PR so that the package can be used with both Python2 and Python3?

**Comment by larroy** [comment]
Care to do it?  I'm not using the library anymore

**Comment by goanpeca** [comment]
@superbobry any progress on this? is this project maintained?

**Comment by superbobry** [comment]
Hello, I'm one of the past contributors and more of a passive observer right now.

**Comment by superbobry** [comment]
Thank you, I've added Python3 support to the `master` version.

**Pull request closed without merging**
